// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw21llLGOGIeEBjZCO03NrvGgBAmTwkhM',
    appId: '1:376405727848:web:9496b968237dde708a79dd',
    messagingSenderId: '376405727848',
    projectId: 'guardiasapp-5519c',
    authDomain: 'guardiasapp-5519c.firebaseapp.com',
    storageBucket: 'guardiasapp-5519c.firebasestorage.app',
    measurementId: 'G-V0NLX1W85B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP3ZV2yIc2OK9xhkqnMItv1qYT5EVT2XM',
    appId: '1:376405727848:android:f454b220021b51738a79dd',
    messagingSenderId: '376405727848',
    projectId: 'guardiasapp-5519c',
    storageBucket: 'guardiasapp-5519c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoih05Hjk98vQY-FSZ_Rff26dcS65v5x0',
    appId: '1:376405727848:ios:4740ab0445decf268a79dd',
    messagingSenderId: '376405727848',
    projectId: 'guardiasapp-5519c',
    storageBucket: 'guardiasapp-5519c.firebasestorage.app',
    iosBundleId: 'com.example.guardiasFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoih05Hjk98vQY-FSZ_Rff26dcS65v5x0',
    appId: '1:376405727848:ios:4740ab0445decf268a79dd',
    messagingSenderId: '376405727848',
    projectId: 'guardiasapp-5519c',
    storageBucket: 'guardiasapp-5519c.firebasestorage.app',
    iosBundleId: 'com.example.guardiasFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw21llLGOGIeEBjZCO03NrvGgBAmTwkhM',
    appId: '1:376405727848:web:042971f51015ac458a79dd',
    messagingSenderId: '376405727848',
    projectId: 'guardiasapp-5519c',
    authDomain: 'guardiasapp-5519c.firebaseapp.com',
    storageBucket: 'guardiasapp-5519c.firebasestorage.app',
    measurementId: 'G-8YNWPV0KC2',
  );
}
